#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for: Fix Rename Directory Operation

set -e

echo "========================================"
echo "Fix Rename Directory Operation - Dev Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# VERIFY .NET SDK
# ============================================

echo ""
echo "Verifying .NET SDK..."

if ! command -v dotnet &> /dev/null; then
    echo -e "${RED}Error: .NET SDK not found${NC}"
    echo "Please install .NET SDK 9.0.0 or compatible version"
    echo "Visit: https://dotnet.microsoft.com/download"
    exit 1
fi

DOTNET_VERSION=$(dotnet --version)
echo -e "${GREEN}.NET SDK version: $DOTNET_VERSION${NC}"

# Check for .NET 8.0 and 9.0 (required by global.json)
if ! dotnet --list-sdks | grep -E "8\.|9\." &> /dev/null; then
    echo -e "${YELLOW}Warning: This project requires .NET 8.0 or 9.0${NC}"
    echo "Detected SDKs:"
    dotnet --list-sdks
fi

# ============================================
# RESTORE DEPENDENCIES
# ============================================

echo ""
echo "Restoring NuGet packages..."
dotnet restore

if [ $? -eq 0 ]; then
    echo -e "${GREEN}Dependencies restored successfully${NC}"
else
    echo -e "${RED}Failed to restore dependencies${NC}"
    exit 1
fi

# ============================================
# BUILD PROJECT
# ============================================

echo ""
echo "Building project..."
dotnet build

if [ $? -eq 0 ]; then
    echo -e "${GREEN}Build succeeded${NC}"
else
    echo -e "${RED}Build failed${NC}"
    exit 1
fi

# ============================================
# RUN TESTS (OPTIONAL - to verify starting state)
# ============================================

echo ""
read -p "Run tests to verify starting state? [y/N] " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "Running unit tests..."
    dotnet test tests/Atypical.VirtualFileSystem.UnitTests/

    if [ $? -eq 0 ]; then
        echo -e "${GREEN}All tests passed${NC}"
    else
        echo -e "${YELLOW}Some tests failed (expected - we're fixing a bug)${NC}"
    fi
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Project: Atypical.VirtualFileSystem"
echo "Task: Fix Rename Directory Operation"
echo ""
echo "Quick Commands:"
echo "  Build:        dotnet build"
echo "  Test:         dotnet test"
echo "  Test Filter:  dotnet test --filter \"FullyQualifiedName~RenameDirectory\""
echo "  Run Demo:     dotnet run --project src/Atypical.VirtualFileSystem.DemoCli/"
echo ""
echo "Next Steps:"
echo "  1. Review implementation_plan.json for subtask breakdown"
echo "  2. Start with phase-1-fix-event-args"
echo "  3. Follow the subtasks sequentially"
echo ""
